# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  funkDir: /home/pints/functional-testing

trigger:
- master

pool:
  name: 'pints-skip'

steps:

- checkout: none # don't actually check out source - we work on an existing directory

- script: git pull
  workingDirectory: $(funkDir)
  displayName: Update pints@skip functional-testing repo

- script: ./funk run opt_fn_XNES --analyse -r 2
  workingDirectory: $(funkDir)
  displayName: Run specific test
  failOnStderr: true

#- script: ./funk run --next --analyse --plot -r 5
#  workingDirectory: $(funkDir)
#  displayName: Run next test
#
#- script: ./funk report
#  workingDirectory: $(funkDir)
#  displayName: Create report
#
#- script: ./funk commit
#  workingDirectory: $(funkDir)
#  displayName: Commit results


