# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-ci

pr: none

jobs:

- job: RunEverything
  
  displayName: Master job to run all steps
  
  variables:
    funkDir: /home/pints/functional-testing

  pool:
    name: 'pints-skip'

  timeoutInMinutes: 0 # run forever (on self-hosted agents like pints-skip)

  steps:

  - checkout: none # don't actually check out source - we work on an existing directory

  - script: git pull
    workingDirectory: $(funkDir)
    displayName: Update pints@skip functional-testing repo

  - script: ./funk run --next --plot -r 5
    workingDirectory: $(funkDir)
    displayName: Run next test
    timeoutInMinutes: 115 # in case test takes a long time, prevent clash with next run

  - script: ./funk analyse --last
    workingDirectory: $(funkDir)
    displayName: Analise test
    failOnStderr: true # this is what reports a failure, due to printing to stderr in __main__.py

  - script: ./funk report
    workingDirectory: $(funkDir)
    displayName: Create report
    condition: always() # run even if the test fails

  - script: ./funk commit
    workingDirectory: $(funkDir)
    displayName: Commit results
    condition: always() # run even if the test fails
